// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/player/:slug": {
    params: {
      "slug": string;
    };
  };
  "/api/proxy": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/player/:slug" | "/api/proxy";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/player.$slug.tsx": {
    id: "routes/player.$slug";
    page: "/player/:slug";
  };
  "routes/api.proxy.ts": {
    id: "routes/api.proxy";
    page: "/api/proxy";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/player.$slug": typeof import("./app/routes/player.$slug.tsx");
  "routes/api.proxy": typeof import("./app/routes/api.proxy.ts");
};